foreground #d0d7e4
background #1c2433
cursor #69C3FF
cursor_text_color #1c2433
selection_foreground #d0d7e4
selection_background #283449
active_tab_foreground #d0d7e4
active_tab_background #181f2c
inactive_tab_foreground #4a5e84
inactive_tab_background #1c2433
color0 #181f2c
color1 #E35535
color2 #3CEC85
color3 #FF955C
color4 #69C3FF
color5 #69C3FF
color6 #22ECDB
color7 #afbbd2
color8 #4a5e84
color9 #E35535
color10 #3CEC85
color11 #FF955C
color12 #69C3FF
color13 #69C3FF
color14 #22ECDB
color15 #d0d7e4
