foreground #e9ecf0
background #333a45
cursor #f44c7f
cursor_text_color #333a45
selection_foreground #e9ecf0
selection_background #503d4e
active_tab_foreground #e9ecf0
active_tab_background #2e343d
inactive_tab_foreground #6d7684
inactive_tab_background #333a45
color0 #2e343d
color1 #da3333
color2 #4cf484
color3 #f4a04c
color4 #f44c7f
color5 #f44c7f
color6 #4cf489
color7 #939eae
color8 #6d7684
color9 #da3333
color10 #4cf484
color11 #f4a04c
color12 #f44c7f
color13 #f44c7f
color14 #4cf489
color15 #e9ecf0
