foreground #e9e2d4
background #16130b
cursor #dfc56d
cursor_text_color #16130b
selection_foreground #e9e2d4
selection_background #38342b
active_tab_foreground #e9e2d4
active_tab_background #221f17
inactive_tab_foreground #979080
inactive_tab_background #16130b
color0 #221f17
color1 #ffb4ab
color2 #d3c6a1
color3 #dfc56d
color4 #dfc56d
color5 #dfc56d
color6 #abd0b0
color7 #cec6b4
color8 #979080
color9 #ffb4ab
color10 #d3c6a1
color11 #dfc56d
color12 #dfc56d
color13 #dfc56d
color14 #abd0b0
color15 #e9e2d4
