set nocompatible

let mapleader=" "
let maplocalleader=" "

filetype on
filetype indent on
filetype plugin on
syntax on

set autoindent
set autoread
set completeopt=menu,popup
set display=lastline
set encoding=UTF-8
set expandtab
set hidden
set history=10000
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set mouse=nvi
set mousemodel=popup_setpos
set nojoinspaces
set nostartofline
set number
set pumheight=8
set relativenumber
set ruler
set cursorline
set sessionoptions-=options
set sessionoptions+=unix,slash
set shiftwidth=2
set showcmd
set sidescroll=1
set smartcase
set smarttab
set softtabstop=2
set splitbelow
set splitright
set switchbuf=uselast
set tabstop=2
set tags=./tags;,tags
set ttimeout
set ttimeoutlen=50
set ttyfast
set wildoptions=pum,tagfile

" To visualize tabs and trailing spaces
set list
set listchars=tab:»\ ,trail:·,nbsp:␣

" Strip trailing white spaces on save
fun! StripTrailingWhitespace()
  " don't strip on these filetypes
  if &ft =~ 'markdown'
    return
  endif
  %s/\s\+$//e
endfun
autocmd BufWritePre * call StripTrailingWhitespace()

set termguicolors

colorscheme gruvbox

" hi Normal guibg=NONE ctermbg=NONE
" hi NonText guibg=NONE ctermbg=NONE
" hi CursorLine cterm=NONE gui=NONE
" hi CursorLineNr cterm=NONE gui=NONE

" Set cursor styles in Normal, Insert, and Command modes
" 1 or 0 -> blinking block
" 2 -> solid block
" 3 -> blinking underline
" 4 -> solid underline
" 5 -> blinking bar
" 6 -> solid bar
autocmd InsertEnter * silent !echo -ne "\e[5 q"
autocmd InsertLeave * silent !echo -ne "\e[2 q"

" vim-plug bootstrap
if empty(glob('~/.config/vim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.config/vim/plugged')

Plug 'bullets-vim/bullets.vim'
Plug 'preservim/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown'
Plug 'ap/vim-css-color'

call plug#end()

nnoremap <silent> <C-l> :set hlsearch!<CR><C-l>
nnoremap <silent> <Esc> :set nohlsearch<CR><C-l>

nnoremap <leader>e :NERDTreeToggle<CR>

nnoremap <leader>v :edit $MYVIMRC<CR>
nnoremap <leader>o :source $MYVIMRC<CR>

nnoremap <leader>ww :write<CR>
nnoremap <leader>wk :e ~/OneDrive/Documents/Weekly.md<CR>

nnoremap <leader>qq :wq<CR>
nnoremap <leader>qa :wqa<CR>

" Smart way to move between windows
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Move Lines
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Make Y behave like C and D
nnoremap Y y$

nnoremap <silent> <Leader>bb :e #<CR>
nnoremap <silent> <Leader>bd :bdelete<CR>
nnoremap <silent> <Leader>bn :bnext<CR>
nnoremap <silent> <Leader>bp :bprevious<CR>

" Useful tricks for keying in the arrow
iabbrev >> →
iabbrev << ←
iabbrev ^^ ↑
iabbrev VV ↓

" Useful tricks for keying in the Chinese quotation marks
inoremap 【【 「
inoremap 】】 」
inoremap 《《 『
inoremap 》》 』

" Abbreviations
iabbrev btw By the way,
iabbrev fyi For your information —
iabbrev asap as soon as possible.
iabbrev fedex FedEx
iabbrev dhl DHL
iabbrev ndl Nolan Digital Limited
iabbrev tcl Twine Company Limited
