[flavor]
light = "bluloco-light"
dark = "catppuccin-macchiato"

# General, Browser, Status Bar, Search, and Progress Bar are handled by flavors.
# Only add overrides here if you want to deviate from the flavor's design.
