require("plugins.blink")
require("plugins.conform")
require("plugins.lualine")
require("plugins.misc")
require("plugins.nvim-lint")
require("plugins.img-clip")
-- require("plugins.nvim-lspconfig")
require("plugins.nvim-surround")
require("plugins.nvim-treesitter")
require("plugins.snacks")
require("plugins.tokyonight")
require("plugins.which-key")
